name: Build site and deploy custom image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build clearnet
        run: hugo --config clearnet_config.yml --destination ./public

      - name: Build Tor
        run: hugo --config tor_config.yml --destination ./tor

      - name: Install zopfli
        run: sudo apt-get install -y --no-install-recommends zopfli

      - name: Compress public static files
        run: |
          cd public
          for file in $(find . -type f)
          do
              zopfli "$file"
              rm "$file"
              touch -r "$file".gz "$file"
          done

      - name: Compress tor static files
        run: |
          cd tor
          for file in $(find . -type f)
          do
              zopfli "$file"
              rm "$file"
              touch -r "$file".gz "$file"
          done

      - name: Build and push to Docker Hub and Github Packages Docker Registry
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sethforprivacy-blog:latest
            ${{ secrets.DOCKER_USERNAME }}/sethforprivacy-blog:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
